### PR TITLE
Add CHANGES file (covering since v0.13.0); easier MD listing standards

### PR DESCRIPTION
**Pull request by brettz9**
Addresses #155 (at least until automation into Github release notes).

### CODE REVIEW

**Comment by brettz9** [comment]
Btw, there is no 13.1 tagged release, but the commit that introduced the number to `package.json`, etc. is https://github.com/aaronpowell/db.js/commit/31b85ab64eec0b2923390e6a2f119f6d859c14a5 and I treated it as a release in CHANGES.

**Comment by brettz9** [comment]
And while I know the dates can be found in the history, I think it is convenient for users to be able to get a quick glance, in case they say wanted to compare their rough idea of the last time they reviewed the code to what the changes have since been.

**Comment by aaronpowell** [comment]
Gone back and retagged that commit so it should be all good now

**Comment by brettz9** [comment]
Cool, thanks!

**Pull request merged**
