### PR TITLE
Allow array of objects to be supplied to update() for batch processin…

### PR DESCRIPTION
**Pull request by brettz9**
…g (paralleling add() behavior), addressing issue #123; add test; simplify add(); rmv trailing spaces

Replacing outdated PR #131 .

Note that some dist/ changes appear to be due to my having just installed babel which was apparently a more recent version than that you used.

### CODE REVIEW

**Comment by brettz9** [comment]
Btw, as I redo my PRs, applying against your current `master`, would you be ok with me fixing the remaining ESLint issues in the test files or do you want to see and address the issues to your liking? (I hope you don't mind the trailing spaces that was a part of this commit; have an Atom package which automatically does that, and seems useful from my perspective to catch)

**Comment by brettz9** [comment]
Also, FYI, I have a number of other PRs to make down the pipeline, but I'm going to avoid the possible trouble of having to redo them by waiting on your approval after each one (before submitting the other PRs).

**Comment by brettz9** [comment]
And as far as ESLint, since I see you utilizing arrow functions and such, do you care to add the ES6 rules at http://eslint.org/docs/rules/#ecmascript-6 (which are not part of the standard package) to e.g., require arrow functions (instead of just allowing them).

**Comment by brettz9** [comment]
And sorry for the spam, but while I'm asking questions that may affect how I shape the PRs...Adding methods on the prototype reduces memory usage (since only one function should be built into memory rather than one for each instance), so I'd just like to confirm you'd be ok with that change.

**Comment by aaronpowell** [comment]
Which version of babel are you using? I only did the setup like a week ago so I wouldn't have expected it to change too drastically.

Regarding having multiple PR's on the go, I have no objection, the problem with the previous few was they seemed to keep building on each other, so the most recent PR would contain all the commits of the previous ones. If they are unique functionality it'd be better to always start from `master` with them.

**Comment by brettz9** [comment]
babel core is showing on their site as 6.1.21 (updated 5 days ago) and that is the version I see in db.js' `node_modules/babel-core/package.json`. I got all of the developer depedencies through a local "npm install".

**Comment by aaronpowell** [comment]
Well I suppose if the tests pass still that's all that really matters ;)

**Pull request merged**
