### PR TITLE
Fix ios8.1 indexedDB null bug

### PR DESCRIPTION
**Pull request by dukex**

### CODE REVIEW

**Comment by dcrec1** [comment]
@aaronpowell this is very useful when on cordova

**Comment by aaronpowell** [comment]
Why not add it to the end of the checks at the start of the file?

**Comment by PedroPinheiro** [comment]
+1

**Comment by dcrec1** [comment]
@aaronpowell, whats the problem with this implementation?

**Comment by aaronpowell** [comment]
I would like all fallback options on a single line for consistency.

Sent from my Windows Phone
________________________________

**Comment by dukex** [comment]
@aaronpowell  like it:
``` js
indexedDB = window.indexedDB || window.webkitIndexedDB || window.mozIndexedDB || window.oIndexedDB || window.msIndexedDB || (window.indexedDB === null && window.shimIndexedDB) ? window.shimIndexedDB : undefined;
```

**Comment by aaronpowell** [comment]
Yep. This way there isn't two conditionals.

**Comment by dukex** [comment]
@aaronpowell done!

**Comment by aaronpowell** [comment]
:shipit:

**Comment by aaronpowell** [comment]
npm + bower + tags updated

**Pull request merged**
