### PR TITLE
All tests passed, the CI should be back now

### PR DESCRIPTION
**Pull request by lygstate**
Fixes tests in server-add.js

### CODE REVIEW

**Comment by lygstate** [comment]
Hi, please merge this pull request.

**Comment by lygstate** [comment]
call for pull request.

**Comment by aaronpowell** [comment]
There is a lot of different unrelated changes in this PR. I've noticed new features, test refactors, promise refactors, bug fixes and replacement of grunt with karma.

Please submit a PR for the individual components so they can be reviewed/accepted independently.

**Comment by lygstate** [comment]
I don't have time to do it, you can review it one by one,

**Comment by lygstate** [comment]
@aaronpowell  Considerating we are at different time zone, you doing this just getting the reivew can be not possible.!

**Comment by lygstate** [comment]
If you think there is need a series of pulls, do it your self, if have problem, tell me after you have really read the code.

**Pull request closed without merging**
