### PR TITLE
Work around Firefox issue when ContraintError occurs

### LINKED ISSUE #98: Firefox throws ConstraintError and aborts hard when key already exists
Seen in FF 35.0 and the previous version on OS X 10.10.

If an attempt is made to add a record when a record with the same key already exists, FF throws a ConstraintError causing the transaction to abort hard without properly rejecting it.

Other browsers don't have this problem.

I think the issue is described here: https://bugzilla.mozilla.org/show_bug.cgi?id=872873

Adding `e.preventDefault()` to the error handler of the `add` function solves it for me:

```js
transaction.onerror = function ( e ) {
     // prevent Firefox from throwing a ConstraintError and aborting (hard)
     e.preventDefault();
     reject( records , e );
};
```

### PR DESCRIPTION
**Pull request by MartijnR**
closes #98

### CODE REVIEW

**Comment by MartijnR** [comment]
Hi Aaron, 

Are you still maintaining this repo? I can wait, but just wanted to check whether I should publish my own port on bower or not.

**Comment by davidsteinberger** [comment]
Ran into the same issue. That indeed fixes it. Thanks for looking into this!

**Comment by aaronpowell** [comment]
Sorry, I must have missed the notification of this PR. Merged now :)

**Comment by MartijnR** [comment]
Thanks!

**Comment by davidsteinberger** [comment]
Thanks much!

**Pull request merged**
